import = [
	"~/.config/alacritty/catppuccin-mocha.toml"
]

[env]
TERM = "xterm-256color"

[font]
size = 14.0

[font.normal]
family = "Agave Nerd Font"

[window]
# history = 10000
# multiplier = 3
opacity = 0.75
blur = false
decorations = "None"

[window.padding]
x = 10
y = 10
