
[env]
TERM = "xterm-256color"

[font]
size = 12.0

[font.normal]
family = "CommitMono Nerd Font"
# style = "Regular"

# [font.bold]
# family = "CodeNewRoman Nerd Font"
# style = "Bold"
#
# [font.bold_italic]
# family = "CodeNewRoman Nerd Font"
# style = "Bold Italic"
#
# [font.italic]
# family = "CodeNewRoman Nerd Font"
# style = "Italic"

[window]
# history = 10000
# multiplier = 3
opacity = 0.85
blur = false
decorations = "Transparent"

[window.padding]
x = 10
y = 30

[general]
import = [
	"~/.config/alacritty/themes/tokyonight.toml"
]
