import = [
	"~/.config/alacritty/catppuccin-mocha.toml"
]

[env]
TERM = "xterm-256color"

[font]
size = 12.0

[font.normal]
family = "BlexMono Nerd Font"
# style = "Medium"

[font.bold]
family = "BlexMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "BlexMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "BlexMono Nerd Font"
style = "Italic"

[window]
# history = 10000
# multiplier = 3
opacity = 0.75
blur = false
decorations = "None"

[window.padding]
x = 10
y = 10
